"""
char_a='A' 
char_b='B'
ascii_a=ord(char_a)
ascii_b=ord(char_b)
print(ascii_a)
print(ascii_b)
"""
char_a=65 
char_b=66
ascii_a=chr(char_a)
ascii_b=chr(char_b)
print(ascii_a)
print(ascii_b)